import type { Metadata } from "next";
import { Geist, Geist_Mono, IBM_Plex_Sans_Arabic } from "next/font/google";
import { Cookie } from "next/font/google";

import "./globals.css";
import { RequestCookie } from "next/dist/compiled/@edge-runtime/cookies";
import { getLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import CurrencyProvider from "@/components/mycomponents/currency/currencyProvider";
import DisplayHeader from "@/functoins/displayHeader";
import DisplayFooter from "@/functoins/displayFooter";
import DisplaySamples from "@/functoins/displaySamples";
import { cookies } from "next/headers";

export const font = Cookie({
  variable: "--font-cookie-sans",
  subsets: ["latin"],
  weight: ["400"],
});
const arabicFont = IBM_Plex_Sans_Arabic({
  subsets: ["arabic", "latin"],
  variable: "--font-myFont",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Ashion",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const cookieTheme: RequestCookie | undefined = cookieStore.get("theme");

  const theme: string = cookieTheme ? cookieTheme.value : "";

  const locale = await getLocale();
  return (
    <html
      lang={locale}
      className={theme}
      data-theme={theme}
      dir={locale == "en" ? "ltr" : "rtl"}
    >
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${arabicFont.variable} antialiased dark:bg-gray-900 dark:text-white`}
      >
        <CurrencyProvider>
          <NextIntlClientProvider>
            <DisplayHeader />

            {children}
            <DisplaySamples />
            <DisplayFooter />
          </NextIntlClientProvider>
        </CurrencyProvider>
      </body>
    </html>
  );
}
