import type { Metadata } from "next";
import { Geist, Geist_Mono, IBM_Plex_Sans_Arabic } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./store-provider";


const arabicFont = IBM_Plex_Sans_Arabic({
  subsets: ["arabic"],
  variable: "--font-arabic",
   weight: ["100", "200", "300", "400", "500", "600", "700"]
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children, 
}: Readonly<{
  children: React.ReactNode,
}>)


{

  return (
    <html lang="en">
      <head>
         
{/* <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin=""/>
   <link
          href="https://fonts.googleapis.com/css2?family=Coda:wght@400;800&family=IBM+Plex+Sans+Arabic:wght@100;200;300;400;500;600;700&display=swap"
          rel="stylesheet"
        /> */}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${arabicFont.variable} antialiased d-flex `}>
      <ReduxProvider>
      <h1 className="text-4xl font-bold mb-6 bg-green-600 text-center">Welcome to My Next.js App</h1>

        {children}
      </ReduxProvider>
      </body>
    </html>
  );
}
